<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <Compile Remove="Constants\**" />
    <Compile Remove="Exceptions\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Constants\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Common\**" />
    <None Remove="Constants\**" />
    <None Remove="Exceptions\**" />
    <None Remove="Extensions\**" />
    <None Remove="Helpers\**" />
  </ItemGroup>

</Project>
