<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <Compile Remove="Controllers\**" />
    <Compile Remove="Filters\**" />
    <Compile Remove="Middleware\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="ViewModels\**" />
    <Content Remove="Configurations\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Filters\**" />
    <Content Remove="Middleware\**" />
    <Content Remove="Models\**" />
    <Content Remove="Services\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Filters\**" />
    <EmbeddedResource Remove="Middleware\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Configurations\**" />
    <None Remove="Controllers\**" />
    <None Remove="Filters\**" />
    <None Remove="Middleware\**" />
    <None Remove="Models\**" />
    <None Remove="Services\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryPlatform.Application\InventoryPlatform.Application.csproj" />
    <ProjectReference Include="..\InventoryPlatform.Infrastructure\InventoryPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\InventoryPlatform.Shared\InventoryPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
