<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Events\**" />
    <Compile Remove="ValueObjects\**" />
    <EmbeddedResource Remove="Events\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="Events\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryPlatform.Shared\InventoryPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
