<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Email\**" />
    <Compile Remove="Logging\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Email\**" />
    <EmbeddedResource Remove="Logging\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Email\**" />
    <None Remove="Logging\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Interceptors\" />
    <Folder Include="Persistence\Seeding\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryPlatform.Application\InventoryPlatform.Application.csproj" />
    <ProjectReference Include="..\InventoryPlatform.Domain\InventoryPlatform.Domain.csproj" />
    <ProjectReference Include="..\InventoryPlatform.Shared\InventoryPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
